FROM node:20-alpine

WORKDIR /app

# ARG NEXT_PUBLIC_INVENTORY_API_URL
# ARG NEXT_PUBLIC_RETAIL_API_URL
# ARG NEXT_PUBLIC_SUPPLYCHAIN_API_URL
# ARG NEXT_PUBLIC_DATASCIENCE_API_URL

# ENV NEXT_PUBLIC_INVENTORY_API_URL=$NEXT_PUBLIC_INVENTORY_API_URL
# ENV NEXT_PUBLIC_RETAIL_API_URL=$NEXT_PUBLIC_RETAIL_API_URL
# ENV NEXT_PUBLIC_SUPPLYCHAIN_API_URL=$NEXT_PUBLIC_SUPPLYCHAIN_API_URL
# ENV NEXT_PUBLIC_DATASCIENCE_API_URL=$NEXT_PUBLIC_DATASCIENCE_API_URL

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm","run","start"]